/**
 * MonoFlow - Common Shared Logic (i18n, Theme, Data)
 */

const CONSTANTS = {
    STORAGE_KEY: 'monoflow-v10-refactored',
    LANG_KEY: 'monoflow-lang',
    THEME_KEY: 'monoflow-theme',
    DONE_COLUMN_ID: 'c3',
    COLORS: {
        red: 'bg-red-100 text-red-700 border-red-200',
        blue: 'bg-blue-100 text-blue-700 border-blue-200',
        green: 'bg-green-100 text-green-700 border-green-200',
        yellow: 'bg-yellow-100 text-yellow-700 border-yellow-200',
        purple: 'bg-purple-100 text-purple-700 border-purple-200'
    },
    PRIORITIES: [
        { value: 'high', label: { ja: '高', en: 'High' }, icon: 'chevrons-up', style: 'text-red-600 bg-red-50 border-red-200' },
        { value: 'medium', label: { ja: '中', en: 'Med' }, icon: 'minus', style: 'text-orange-600 bg-orange-50 border-orange-200' },
        { value: 'low', label: { ja: '低', en: 'Low' }, icon: 'chevrons-down', style: 'text-blue-600 bg-blue-50 border-blue-200' },
        { value: 'none', label: { ja: '指定なし', en: 'None' }, icon: '', style: 'text-slate-600 bg-slate-100 border-slate-300' }
    ],
    I18N: {
        ja: {
            app_desc: 'Simple Personal Kanban',
            back_to_app: 'アプリに戻る',
            filter_label: 'ラベル',
            filter_all: 'すべてのラベル',
            filter_priority_all: 'すべての優先度',
            add_placeholder: '新しいタスクを入力...', 
            add_btn: '追加',
            search_placeholder: '検索...',
            menu_board: 'ボード',
            menu_export: 'エクスポート (JSON)',
            menu_import: 'インポート',
            menu_metrics: 'Metrics',
            menu_burndown: 'Burndown',
            menu_archive: 'アーカイブ',
            menu_about: 'About',
            menu_help: 'User Guide',
            menu_reset: 'ボードのリセット',
            modal_title: 'タスク詳細',
            modal_label_title: 'タイトル',
            modal_label_priority: '優先度',
            modal_label_tags: 'ラベル',
            modal_label_new_tag: '新しいラベル名',
            modal_btn_add_tag: '追加',
            modal_label_parent: '親タスク',
            modal_label_none: '(なし)',
            modal_label_desc: '詳細メモ',
            modal_label_date: '期限',
            modal_btn_cancel: 'キャンセル',
            modal_btn_save: '保存',
            modal_btn_archive: 'アーカイブする',
            modal_btn_unarchive: 'ボードに戻す',
            col_todo: '未着手',
            col_progress: '進行中',
            col_done: '完了',
            task_created: '作成',
            task_updated: '更新',
            task_completed: '完了',
            confirm_delete: 'タスクを削除しますか？',
            confirm_reset_1: '【警告】すべてのタスクを完全に削除しますか？\nこの操作は取り消せません。',
            confirm_reset_2: '本当に削除しますか？\n削除前に「エクスポート」してバックアップを取っておくことをお勧めします。',
            reset_done: 'ボードをリセットしました。',
            import_done: 'インポートが完了しました。',
            import_fail: 'インポートに失敗しました。',
            welcome_title: 'Welcome to MonoFlow',
            welcome_desc: 'これはサンプルタスクです。',
            // Page Titles
            metrics_title: 'MonoFlow',
            metrics_subtitle: '分析と進捗',
            metrics_period: '期間',
            metrics_total: '全タスク数',
            metrics_rate: '完了率',
            metrics_avg: '平均完了日数',
            metrics_done: '合計完了数',
            metrics_dist: 'ステータス分布',
            metrics_prio_dist: '優先度別の分布',
            metrics_label_select: 'ラベルを選択',
            metrics_clear: 'クリア',
            burndown_title: 'MonoFlow',
            burndown_subtitle: '時間経過による残仕事量',
            burndown_period: '表示期間',
            burndown_trend: '残タスク数の推移',
            burndown_current: '現在',
            burndown_actual: '実際の残りタスク',
            burndown_ideal: '理想的な進捗',
            help_title: 'MonoFlow',
            help_subtitle: '操作マニュアル',
            help_quick: 'クイックスタート',
            help_manual: '詳細マニュアル',
            help_q1_t: 'タスクの作成',
            help_q1_d: '上部の大きな入力欄に内容を書き込み Enter を押すだけ。瞬時にチケットが発行されます。',
            help_q2_t: '進捗の管理',
            help_q2_d: 'カードをドラッグしてレーン間を移動。Doneへ移動させると「完了スタンプ」が自動で押されます。',
            help_q3_t: '情報の詳細化',
            help_q3_d: 'カードをクリックして詳細パネルへ。優先度の設定、メモの追記、ラベルでの分類が行えます。',
            help_m1_t: '1. タスクカードの構造',
            help_m1_d: 'MonoFlowのタスクカードは、限られたスペースに多くの情報を凝縮して表示するように設計されています。',
            help_m1_h1: '視覚的インジケータ',
            help_m1_l1: '優先度アクセント: カード左端の太いラインで重要度を表現。',
            help_m1_l2: 'タイムスタンプ: 右下に作成日時と最終更新日時を自動表示。',
            help_m1_l3: 'メモプレビュー: タイトルの下に詳細メモの冒頭2行を自動でプレビュー。',
            help_m1_l4: '状態バッジ: 期限切れは赤色、完了済みは緑色のバッジで強調。',
            help_m1_h2: '完了時の挙動',
            help_m1_l5: 'グレーアウト: Doneレーンにあるタスクは透明度を下げ、集中を妨げないようにします。',
            help_m1_l6: '打ち消し線: タイトルに線を引き、完了したことを明示。',
            help_m1_l7: '完了時刻: 完了した瞬間の「時・分」を正確に記録し表示します。',
            help_m2_t: '2. 高度な親子関係と「仮想チケット」',
            help_m2_d: '複雑なタスクをサブタスクに分割して管理できます。MonoFlow独自の「仮想チケット」システムが情報の断絶を防ぎます。',
            help_m2_h1: '仮想親チケット (Virtual Parent)',
            help_m2_l1: '子タスクが親と別のレーンにあるとき、子の上に親の「残像」が表示されます。',
            help_m2_h2: '仮想子チケット (Virtual Child)',
            help_m2_l2: '親タスクの下には、他レーンに散らばった子タスクの状況が一覧表示されます。',
            help_m2_h3: 'ジャンプ機能',
            help_m2_l3: '仮想チケットをクリックすると、実体のある場所まで自動スクロールし、フラッシュして知らせます。',
            help_m2_extra: '親タスクにはサブタスクの消化状況が表示されます。完了数に応じてプログレスバーも伸びていきます。',
            help_m3_t: '3. 検索とフィルタリング',
            help_m3_d: '数千のタスクがあっても、目的の情報を数秒で見つけ出すことができます。',
            help_m3_h1: '全文検索',
            help_m3_l1: 'ツールバーの検索窓にキーワードを入力すると、リアルタイムで絞り込みます。',
            help_m3_h2: 'マルチフィルタ',
            help_m3_l2: 'ラベルと優先度の2つのフィルターを組み合わせて詳細な絞り込みが可能です。',
            help_m4_t: '4. 分析とデータ管理',
            help_m4_d: 'MonoFlowは単なるToDoリストではなく、あなたの生産性を分析するパートナーです。',
            help_m4_h1: '進捗の可視化',
            help_m4_l1: 'MetricsやBurndownで、ステータス分布や進捗ペースをグラフで確認できます。',
            help_m4_h2: 'アーカイブと整理',
            help_m4_l2: '完了したタスクをアーカイブへ移動させることで、ボードを常にクリーンに保てます。',
            help_m4_h3: 'バックアップ',
            help_m4_l3: 'JSON形式でのエクスポート・インポートに対応。データ移行も簡単です。',
            help_m4_privacy_t: 'データプライバシー',
            help_m4_privacy_d: 'すべてのデータはあなたのブラウザ（LocalStorage）にのみ保存されます。外部サーバーへの送信は一切行われないため、機密情報も安全に管理できます。',
            help_m5_t: '5. カスタマイズと設定',
            help_m5_h1: 'ダークモード',
            help_m5_l1: '月アイコンをクリックして切り替え。深夜の作業でも目に優しく集中できます。',
            help_m5_h2: 'マルチ言語対応',
            help_m5_l2: 'メニューから日本語と英語を切り替えられます。',
            help_shortcuts_t: 'キーボードショートカット',
            help_shortcuts_n: '新規タスク入力にフォーカス',
            help_shortcuts_search: '検索窓にフォーカス',
            help_shortcuts_esc: '閉じる / フォーカスを外す',
            help_shortcuts_help: 'ヘルプページを表示',
            help_shortcuts_metrics: 'Metrics ページへ移動',
            help_shortcuts_burndown: 'Burndown ページへ移動',
            help_footer: 'MonoFlow Productivity System - Built for High-Performance Personal Kanban',
            about_title: 'MonoFlow',
            about_link: 'What is MonoFlow?',
            about_subtitle: 'ミニマルで強力な個人用カンバン',
            about_concept_t: 'コンセプト',
            about_concept_d: 'MonoFlowは、個人の生産性を最大化するために設計された、ブラウザ完結型のカンバンツールです。複雑な設定やサーバーは不要。開いた瞬間から、あなたの思考をフロー状態へと導きます。',
            about_features_t: '主な特徴',
            about_f1_t: 'プライバシー第一',
            about_f1_d: 'データは100%ローカル（あなたのブラウザ）に保存されます。外部サーバーへの送信は一切ありません。',
            about_f2_t: '高度な親子関係',
            about_f2_d: '仮想チケットシステムにより、レーンをまたいだ複雑なプロジェクト構造も直感的に把握できます。',
            about_f3_t: '分析機能',
            about_f3_d: 'メトリクスとバーンダウンチャートで、自分のパフォーマンスを客観的に評価できます。'
        },
        en: {
            app_desc: 'Simple Personal Kanban',
            back_to_app: 'Back to App',
            filter_label: 'Label',
            filter_all: 'All Labels',
            filter_priority_all: 'All Priorities',
            add_placeholder: 'Add a new task...', 
            add_btn: 'Add',
            search_placeholder: 'Search...', 
            menu_board: 'Board',
            menu_export: 'Export (JSON)',
            menu_import: 'Import',
            menu_metrics: 'Metrics',
            menu_burndown: 'Burndown',
            menu_archive: 'Archive',
            menu_about: 'About',
            menu_help: 'User Guide',
            menu_reset: 'Reset Board',
            modal_title: 'Task Details',
            modal_label_title: 'Title',
            modal_label_priority: 'Priority',
            modal_label_tags: 'Labels',
            modal_label_new_tag: 'New Label Name',
            modal_btn_add_tag: 'Add',
            modal_label_parent: 'Parent Task',
            modal_label_none: '(None)',
            modal_label_desc: 'Notes',
            modal_label_date: 'Due Date',
            modal_btn_cancel: 'Cancel',
            modal_btn_save: 'Save',
            modal_btn_archive: 'Archive',
            modal_btn_unarchive: 'Restore to Board',
            col_todo: 'To Do',
            col_progress: 'In Progress',
            col_done: 'Done',
            task_created: 'Created',
            task_updated: 'Updated',
            task_completed: 'Done',
            confirm_delete: 'Delete this task?',
            confirm_reset_1: '[WARNING] Are you sure you want to delete ALL tasks?\nThis cannot be undone.',
            confirm_reset_2: 'Are you absolutely sure?\nWe strongly recommend exporting a backup first.',
            reset_done: 'Board has been reset.',
            import_done: 'Import successful.',
            import_fail: 'Import failed.',
            welcome_title: 'Welcome to MonoFlow',
            welcome_desc: 'This is a sample task.',
            // Page Titles
            metrics_title: 'MonoFlow',
            metrics_subtitle: 'Analytics & Progress',
            metrics_period: 'Period',
            metrics_total: 'Total Tasks',
            metrics_rate: 'Comp. Rate',
            metrics_avg: 'Avg Lead Time',
            metrics_done: 'Total Done',
            metrics_dist: 'Status Distribution',
            metrics_prio_dist: 'Priority Distribution',
            metrics_label_select: 'Select Labels',
            metrics_clear: 'Clear',
            burndown_title: 'MonoFlow',
            burndown_subtitle: 'Work Remaining Over Time',
            burndown_period: 'Date Range',
            burndown_trend: 'Work Remaining Trend',
            burndown_current: 'Now',
            burndown_actual: 'Actual Remaining',
            burndown_ideal: 'Ideal Progress',
            help_title: 'MonoFlow',
            help_subtitle: 'Operating Manual',
            help_quick: 'Quick Start',
            help_manual: 'Detailed Manual',
            help_q1_t: 'Create Task',
            help_q1_d: 'Simply type in the large input field at the top and press Enter. A ticket is created instantly.',
            help_q2_t: 'Manage Progress',
            help_q2_d: 'Drag and drop cards between lanes. Moving to Done automatically adds a completion timestamp.',
            help_q3_t: 'Add Details',
            help_q3_d: 'Click a card to open the details panel. Set priority, add notes, and categorize with labels.',
            help_m1_t: '1. Task Card Structure',
            help_m1_d: 'MonoFlow task cards are designed to condense a lot of information into a limited space.',
            help_m1_h1: 'Visual Indicators',
            help_m1_l1: 'Priority Accent: Colored left border indicates importance level.',
            help_m1_l2: 'Timestamps: Created and updated times are automatically displayed.',
            help_m1_l3: 'Note Preview: First two lines of notes are shown below the title.',
            help_m1_l4: 'Status Badge: Overdue tasks are red, completed tasks are green.',
            help_m1_h2: 'Completion Behavior',
            help_m1_l5: 'Gray-out: Tasks in Done lane are dimmed to reduce visual noise.',
            help_m1_l6: 'Strikethrough: Titles are struck through to clearly indicate completion.',
            help_m1_l7: 'Done Time: The exact time of completion is recorded and displayed.',
            help_m2_t: '2. Hierarchy & Virtual Tasks',
            help_m2_d: 'Divide complex tasks into subtasks. MonoFlow\'s unique "Virtual Ticket" system prevents information loss.',
            help_m2_h1: 'Virtual Parent',
            help_m2_l1: 'When a subtask is in a different lane from its parent, a placeholder of the parent is shown above.',
            help_m2_h2: 'Virtual Child',
            help_m2_l2: 'Under the parent, subtasks located in other lanes are shown as a compact list.',
            help_m2_h3: 'Jump Feature',
            help_m2_l3: 'Click any virtual ticket to instantly scroll and flash the real card.',
            help_m2_extra: 'Parents show a progress counter and bar reflecting the completion status of subtasks.',
            help_m3_t: '3. Search & Filtering',
            help_m3_d: 'Find the information you need in seconds, even with thousands of tasks.',
            help_m3_h1: 'Full-text Search',
            help_m3_l1: 'Type in the search box to filter by title and notes in real-time.',
            help_m3_h2: 'Multi-filter',
            help_m3_l2: 'Combine label and priority filters for powerful data slicing.',
            help_m4_t: '4. Analytics & Data Management',
            help_m4_d: 'MonoFlow is not just a ToDo list; it\'s a partner in analyzing your productivity.',
            help_m4_h1: 'Visualization',
            help_m4_l1: 'Use Metrics and Burndown charts to understand your pace and distribution.',
            help_m4_h2: 'Archive',
            help_m4_l2: 'Move completed tasks to the archive to keep your board clean.',
            help_m4_h3: 'Backup',
            help_m4_l3: 'Support for JSON export/import. Easy to migrate data between PCs.',
            help_m4_privacy_t: 'Data Privacy',
            help_m4_privacy_d: 'All your data is stored locally in your browser (LocalStorage). No data is sent to any external server, ensuring your sensitive information stays private.',
            help_m5_t: '5. Customization',
            help_m5_h1: 'Dark Mode',
            help_m5_l1: 'Switch via the moon icon. Easy on the eyes during late-night sessions.',
            help_m5_h2: 'Multilingual',
            help_m5_l2: 'Switch between Japanese and English via the top toolbar.',
            help_shortcuts_t: 'Keyboard Shortcuts',
            help_shortcuts_n: 'Focus New Task Input',
            help_shortcuts_search: 'Focus Search Bar',
            help_shortcuts_esc: 'Close / Blur Input',
            help_shortcuts_help: 'Show Help Page',
            help_shortcuts_metrics: 'Go to Metrics Page',
            help_shortcuts_burndown: 'Go to Burndown Page',
            help_footer: 'MonoFlow Productivity System - Built for High-Performance Personal Kanban',
            // About Page
            about_title: 'About MonoFlow',
            about_link: 'What is MonoFlow?',
            about_subtitle: 'Minimal yet Powerful Personal Kanban',
            about_concept_t: 'Concept',
            about_concept_d: 'MonoFlow is a browser-based Kanban tool designed to maximize individual productivity. No complex setup or servers required. From the moment you open it, it guides your thoughts into a flow state.',
            about_features_t: 'Key Features',
            about_f1_t: 'Privacy First',
            about_f1_d: '100% of your data is stored locally in your browser. No data is ever sent to external servers.',
            about_f2_t: 'Advanced Hierarchy',
            about_f2_d: 'The Virtual Ticket system allows you to intuitively grasp complex project structures across multiple lanes.',
            about_f3_t: 'Built-in Analytics',
            about_f3_d: 'Evaluate your performance objectively with integrated Metrics and Burndown charts.'
        }
    }
};

const State = {
    data: null,
    filter: 'all',
    priorityFilter: 'all',
    searchQuery: '',
    language: 'ja',
    theme: 'light',
    tempLabels: [],
    lastAddedId: null
};

const Common = {
    t: (key) => (CONSTANTS.I18N[State.language] && CONSTANTS.I18N[State.language][key]) || key,
    
    init: () => {
        State.language = localStorage.getItem(CONSTANTS.LANG_KEY) || (navigator.language.startsWith('ja') ? 'ja' : 'en');
        State.theme = localStorage.getItem(CONSTANTS.THEME_KEY) || 'light';
        Common.applyTheme();
        
        // Global Click to close menu
        document.addEventListener('click', () => {
            const menu = document.getElementById('settings-menu');
            if (menu) menu.classList.add('hidden');
        });
    },

    applyTheme: () => {
        const dark = State.theme === 'dark';
        document.documentElement.classList.toggle('dark', dark);
        const lightIcon = document.getElementById('theme-icon-light');
        const darkIcon = document.getElementById('theme-icon-dark');
        if (lightIcon) lightIcon.classList.toggle('hidden', !dark);
        if (darkIcon) darkIcon.classList.toggle('hidden', dark);
    },

    toggleTheme: () => {
        State.theme = State.theme === 'light' ? 'dark' : 'light';
        localStorage.setItem(CONSTANTS.THEME_KEY, State.theme);
        Common.applyTheme();
    },

    toggleMenu: (e) => {
        e.stopPropagation();
        const menu = document.getElementById('settings-menu');
        if (menu) menu.classList.toggle('hidden');
    },

    setLanguage: (lang) => {
        State.language = lang;
        localStorage.setItem(CONSTANTS.LANG_KEY, lang);
        location.reload(); 
    }
};

// Auto-init common logic
Common.init();